CREATE TABLE messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTENIDO VARCHAR(500) NOT NULL,
    ID_EMISOR BIGINT NOT NULL,
    ID_RECEPTOR BIGINT NOT NULL,
    FECHA_ENVIO DATETIME NOT NULL,
    LEIDO BOOLEAN NOT NULL
);