spring.application.name=Auth

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@oj1jsry5oq5a4c36_high?TNS_ADMIN=/Users/{WALLET}
spring.datasource.username=futuroauth
spring.datasource.password=cllampinbombin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

