server.port=8067

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:33067/community_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin_password
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.user=root
spring.flyway.password=admin_password

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.generate-ddl=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.keepalive-time=30000